version: '3.8'
services:
  ocean-market:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocean-market
    ports:
      - '8008:8008'
    environment:
      NODE_ENV: production
    restart: unless-stopped
